### PR TITLE
Added: override ability for `notification_link`

### PR DESCRIPTION
**Pull request by HNKNTA**
Added one field to override, probably some other fields could be added as well, but I haven't tested. The Links overriding seems working fine.
I don't know the approach to manage the changelog, so kept as is.

### CODE REVIEW

**Comment by samuelthng** [comment]
Hey @HNKNTA, thank you for the contribution! I'll add the changelogs after your PR 🙏🏻
Do allow me some time tho, still travelling for this period, will look into it at the head of the year.

**Review by samuelthng — APPROVED** [review]
Change looks good, approving.

**Comment by HNKNTA** [comment]
Hi @samuelthng, thanks for the fast reaction time despite the holiday season! 
I have one question though, currently the flow assumes that user should set options and the script runs forever. And I cannot make the script stop, if I don't have any options and timeout enabled, I guess because of this:
https://github.com/samuelthng/t-house-blueprints/blob/main/notifications.yaml#L1130
Is it something expected and I just didn't get the logic?

**Comment by samuelthng** [comment]
> Hi @samuelthng, thanks for the fast reaction time despite the holiday season! 
> I have one question though, currently the flow assumes that user should set options and the script runs forever. And I cannot make the script stop, if I don't have any options and timeout enabled, I guess because of this:
> https://github.com/samuelthng/t-house-blueprints/blob/main/notifications.yaml#L1130
> Is it something expected and I just didn't get the logic?

I think it is expected, since the timeout is the only signal the script can rely on to proceed to completion. Without the timeout enabled (correct me if I misunderstood), the script will just stop on the response step until it either receives a response for the given notification, or gets killed.

I'll have to explore an event based approach to solve this but no promises.

**Comment by samuelthng** [comment]
The above is correct as per my initial descriptions as well.

**Comment by HNKNTA** [comment]
I guess the whole thing is because of the line I've mentioned above
https://github.com/samuelthng/t-house-blueprints/blob/main/notifications.yaml#L1130

So when timeout is enabled and the time is out, the script still waits for something, even if there are no actions to wait for. Probably this bool value should be parametrized as well.

**Comment by samuelthng** [comment]
> I guess the whole thing is because of the line I've mentioned above
> https://github.com/samuelthng/t-house-blueprints/blob/main/notifications.yaml#L1130
> 
> So when timeout is enabled and the time is out, the script still waits for something, even if there are no actions to wait for. Probably this bool value should be parametrized as well.

Not related to the highlighted line.

If timeout is enabled, script will wait for an event trigger for the configured duration. That is expected. After the timeout countdown completes, it continues the script. That is expected.

The "script running indefinitely" issue you have pointed out is only possible in the case where timeout is not enabled. In other words, the script is expecting a response forever until it is killed (either by another instance or manually or due to HA restarting). This is also expected and should not be parameterised.

**Pull request merged**
