### PR TITLE
Update notifications.yaml

### PR DESCRIPTION
**Pull request by Trilis29**
Hello, this is my rough implementation critical sound level.. If it fits for you, you can merge :)

### CODE REVIEW

**Comment by samuelthng** [comment]
Hey @Trilis29, really appreciate the PR!

There seems to be a big number of changes that's probably added due to your lint config, such as emoji, multi line string formatting and quotes.

Could you perhaps stage only the changes related to critical volume?

**Review by samuelthng — CHANGES_REQUESTED** [review]
Holding merge due to a large number of changes across the board.

**Comment by samuelthng** [comment]
Closing due to inactivity, also, this feature has been implemented in v2.0.2-beta-2

**Comment by Trilis29** [comment]
Missed the email, tomorrow will import

**Pull request closed without merging**
