### PR TITLE
Update syntax for template conditions

### PR DESCRIPTION
**Pull request by ChrisBaker97**
By refactoring the template conditions under the choose action, they become editable in the visual editor, rather than YAML-only.

### CODE REVIEW

**Comment by samuelthng** [comment]
Hey @ChrisBaker97  - again, thank you for the PR.

What visual editor is this meant for?
The conditions are not originally meant to be user editable.

I'm assuming this PR is made in conjunction to PR https://github.com/samuelthng/t-house-blueprints/pull/14, where the script was used as an `automation` rather than a script blueprint.

I think this might be a case of incorrect usage, do let me know if placing the file in `/config/blueprint/script/<whatever/notification.yaml` inteferes any of your use cases.

**Comment by samuelthng** [comment]
Leaving open until reply.

**Comment by ChrisBaker97** [comment]
You're correct that I'm referring to the visual editor in the automation interface. I had borrowed some chunks of your code to get a rather complex automation I've been constructing working with actionable notifications, and this small modification enables the visual editor on those template conditions, which work the same either way, but are limited to YAML editing in automations as originally written.

After understanding the intended script usage, I left my modifications in and placed this into my `blueprints/script` folder instead (changing the `domain` back to `script`, of course), and did some brief testing, including selecting either of the two action choices, swipe to dismiss, and timeout, and it still seems to work as intended as a script. So, if you agree, I'd suggest incorporating these changes anyway, as the script operation appears to be identical, but if anyone else grabs some or all of this code to use in an automation, it will make their experience better by keeping the visual editor enabled for the entire thing.

**Comment by samuelthng** [comment]
Thank you for the response, while it does make sense that it'll work eitherway, I don't think I'll be merging this PR based on the fact that it's not meant to be user facing and I will not be supporting users who will be using the script outside of what I've tested myself.

Appreciate the PRs though!

**Pull request closed without merging**
